version: "2"

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocritic
    - revive
    - bodyclose
    - noctx

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

    gocritic:
      enabled-tags:
        - diagnostic
        - style

  disable:
    - errcheck

  exclusions:
    paths:
      - db/generated
