version: "2"

run:
  exclude-dirs:
    - db/generated

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - revive
    - bodyclose
    - noctx

  settings:
    revive:
      rules:
        - name: exported
          disabled: true

    gocritic:
      enabled-tags:
        - diagnostic
        - style
